### PR TITLE
[BB-870] Add filebeat config for vault logs.

### PR DESCRIPTION
**Pull request by UmanShahzad**
Test Instructions:

1. Go to logs.opencraft.com
1. Go to the "Discover" page
1. Give search query `type: vault`
1. Ensure logs are showing up

### CODE REVIEW

**Comment by always-boycott-github** [comment]
- [x]    Go to logs.opencraft.com
- [x]    Go to the "Discover" page
- [x]    Give search query type: vault
- [ ]    Ensure logs are showing up

**Comment by always-boycott-github** [comment]
When I enter **type: vault** I get nothing. It is entirely possible I'm doing something very stupid: my Kibana foo is nil :smiley: 

s

**Comment by UmanShahzad** [comment]
@always-boycott-github I think the time range you used may have been too little. On the top right bar you can see a relative range like "last 15 minutes" - change that to last 24 hours.

**Comment by always-boycott-github** [comment]
@UmanShahzad thanks for the guidance :-) It works as advertised :tada:

**Pull request merged**
