### PR TITLE
feat: implement vault based SSH

### PR DESCRIPTION
**Pull request by gabor-boros**
This PR implements Vault based SSH authentication for generic servers. We do not include this to common-server-init as we don't want everyone to have access to all servers. More info on this: https://tasks.opencraft.com/browse/SE-6299

**Test instructions**

0. Set the Vault address `export VAULT_ADDR="https://vault.opencraft.com"`
1. Log in to vault `vault login -method="github"`
2. Generate a new ssh key pair with empty passphrase for testing purposes (name should be: `se_5700`)
3. Request Vault to sign your **public** key.
    ```
    vault write -field=signed_key \
        ssh-client-signer/sign/ssh-client-signer-role \
        valid_principals="ubuntu,root" \
        public_key=@~/.ssh/se_5700.pub > ~/.ssh/se_5700-cert.pub
    ```
4. Open an SSH connection to `cert-manager`, using the command below (note that we use the **private** key here, the `-cert.pub` is automatically loaded due to naming conventions).
    ```
    ssh -i ~/.ssh/se_5700 ubuntu@cert-manager.net.opencraft.hosting
    ```

### CODE REVIEW

**Review by mtyaka — APPROVED** [review]
:+1:

- [x] I tested this: I followed the testing instructions to successfully log into the cert-manager VM.
- [x] I read through the code

**Comment by mtyaka** [comment]
@gabor-boros I'm a bit confused by

> We do not include this to common-server-init as we don't want everyone to have access to all servers. 

because this PR does add it to `common-server-init`?

**Comment by gabor-boros** [comment]
@mtyaka oh, I forgot to push latest changes that is deployed to the server. I need 5 mins

**Comment by mtyaka** [comment]
Looks good @gabor-boros 😎 👍

**Pull request merged**
